### ISSUE TITLE
RN > 0.47 Support

### ISSUE THREAD

**Issue by satishmane** [UCSD/react-native-google-api-availability-bridge#2]
googleapiavailabilitybridge/ReactNativeGooglePlayServicesPackage.java:18: error: method does not override or implement a method from a supertype
    @Override

As result of RN 0.47, this error is coming. Can we please get fix.

**Comment by i8wu** [comment]
Do you mean > ?

**Comment by satishmane** [comment]
Yes, I meant >. Sorry typo

**Comment by i8wu** [comment]
https://github.com/UCSD/react-native-google-api-availability-bridge/pull/5
