### ISSUE TITLE
Add additional repository

### ISSUE THREAD

**Issue by mcorner** [UCSD/react-native-google-api-availability-bridge#8]
Because of this disaster: https://issuetracker.google.com/issues/120759347#comment27

This library won't build ATM.  Consider adding another repo to the list in your build.gradle file:

```
repositories {
        mavenCentral()
        jcenter()
    }
```

**Comment by c3bryant** [comment]
Hi @mcorner,
Thank you for submitting this issue - what a mess indeed. Would you mind testing again before we commit this change? It appears this issue may be resolved now: https://issuetracker.google.com/issues/120759347#comment106

If not I will publish your recommended change. We also welcome PR's.

**Comment by mcorner** [comment]
I tested it locally and it works. But the change is optional if you think this won't happen again.  Though this was the only library (out of many) that broke for us.

**Comment by c3bryant** [comment]
We'll move with forward on a resolution if the issue resurfaces. Closing
